import type {
  ActivityItem,
  EstablishmentDetail,
  EstablishmentRow,
  MetricPoint,
  PlanRow,
  SecondaryMetric,
} from "./types";
// plan types expanded in mock-data for Plans / Subscriptions / etc.

export const overviewKpis = [
  {
    label: "MRR",
    value: "R$ 48.260",
    delta: 4.2,
    trend: "up" as const,
    context: "vs. 30 dias",
  },
  {
    label: "ARR",
    value: "R$ 579.120",
    delta: 3.1,
    trend: "up" as const,
    context: "vs. 30 dias",
  },
  {
    label: "Active Businesses",
    value: "184",
    delta: 2.4,
    trend: "up" as const,
    context: "vs. 30 dias",
  },
  {
    label: "Churn",
    value: "1,8%",
    delta: -0.3,
    trend: "up" as const,
    context: "vs. 30 dias · ↓",
  },
];

export const secondaryMetrics: SecondaryMetric[] = [
  { label: "Net New MRR", value: "R$ 3.420", delta: 8.1 },
  { label: "MRR Growth", value: "8,6%", delta: 0.4 },
  { label: "Trial → Paid", value: "34%", delta: 2.1 },
  { label: "ARPU", value: "R$ 262", delta: 1.2 },
  { label: "MRR at Risk", value: "R$ 8.420", delta: -1.1 },
  { label: "Novos clientes", value: "612", delta: 5.0 },
];

export const metricSeries: MetricPoint[] = [
  { period: "Jan", mrr: 32000, arr: 384000, users: 980, activeBusinesses: 142 },
  { period: "Fev", mrr: 34500, arr: 414000, users: 1100, activeBusinesses: 152 },
  { period: "Mar", mrr: 36100, arr: 433200, users: 1220, activeBusinesses: 158 },
  { period: "Abr", mrr: 38200, arr: 458400, users: 1340, activeBusinesses: 165 },
  { period: "Mai", mrr: 39800, arr: 477600, users: 1410, activeBusinesses: 170 },
  { period: "Jun", mrr: 41200, arr: 494400, users: 1480, activeBusinesses: 174 },
  { period: "Jul", mrr: 42800, arr: 513600, users: 1550, activeBusinesses: 178 },
  { period: "Ago", mrr: 44200, arr: 530400, users: 1610, activeBusinesses: 181 },
  { period: "Set", mrr: 48260, arr: 579120, users: 1720, activeBusinesses: 184 },
];

export const plans: PlanRow[] = [
  {
    id: "pro",
    name: "Pro",
    subscribers: 78,
    mrr: 18420,
    growth: 3.4,
    churn: 1.2,
    revenueShare: 38,
  },
  {
    id: "starter",
    name: "Starter",
    subscribers: 96,
    mrr: 12120,
    growth: 1.1,
    churn: 2.4,
    revenueShare: 25,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    subscribers: 12,
    mrr: 13200,
    growth: 6.8,
    churn: 0.4,
    revenueShare: 27,
  },
  {
    id: "trial",
    name: "Trial",
    subscribers: 34,
    mrr: 0,
    growth: 0,
    churn: 0,
    revenueShare: 10,
  },
];

export const activities: ActivityItem[] = [
  {
    id: "a1",
    type: "establishment",
    description: "Studio Bella iniciou o plano Pro.",
    entity: "Studio Bella",
    at: "2026-09-05 09:14",
    status: "success",
  },
  {
    id: "a2",
    type: "establishment",
    description: "Novo estabelecimento cadastrado.",
    entity: "Casa & Arte",
    at: "2026-09-05 08:42",
    status: "info",
  },
  {
    id: "a3",
    type: "subscription",
    description: "Assinatura cancelada.",
    entity: "Loja Norte",
    at: "2026-09-05 07:21",
    status: "warning",
  },
  {
    id: "a4",
    type: "payment",
    description: "Pagamento falhou (PIX).",
    entity: "Pagamento #4821",
    at: "2026-09-04 18:03",
    status: "danger",
  },
  {
    id: "a5",
    type: "admin",
    description: "Admin alterou configuração de plans.",
    entity: "Maria (Finance)",
    at: "2026-09-04 16:40",
    status: "info",
  },
];

export const establishments: EstablishmentRow[] = [
  {
    id: "est-1",
    name: "Studio Bella",
    owner: "Ana Costa",
    plan: "Pro",
    status: "active",
    mrr: 890,
    createdAt: "2026-06-12",
    lastAccess: "2026-09-05 09:10",
    professionals: 4,
    customers: 128,
    utilization: 82,
    churnRisk: "low",
  },
  {
    id: "est-2",
    name: "Casa & Arte",
    owner: "João Lima",
    plan: "Starter",
    status: "trial",
    mrr: 0,
    createdAt: "2026-08-28",
    lastAccess: "2026-09-04 21:12",
    professionals: 2,
    customers: 34,
    utilization: 41,
    churnRisk: "medium",
  },
  {
    id: "est-3",
    name: "Loja Norte",
    owner: "Patrícia M.",
    plan: "Pro",
    status: "active",
    mrr: 1240,
    createdAt: "2025-11-03",
    lastAccess: "2026-09-01 11:04",
    professionals: 6,
    customers: 210,
    utilization: 67,
    churnRisk: "high",
  },
  {
    id: "est-4",
    name: "Nuvem Studio",
    owner: "Carlos R.",
    plan: "Enterprise",
    status: "active",
    mrr: 2680,
    createdAt: "2025-08-19",
    lastAccess: "2026-09-05 08:00",
    professionals: 11,
    customers: 420,
    utilization: 91,
    churnRisk: "low",
  },
  {
    id: "est-5",
    name: "Bar da Rua",
    owner: "Marta S.",
    plan: "Starter",
    status: "inactive",
    mrr: 240,
    createdAt: "2025-12-01",
    lastAccess: "2026-08-22 14:00",
    professionals: 1,
    customers: 18,
    utilization: 12,
    churnRisk: "high",
  },
  {
    id: "est-6",
    name: "Luz & Formato",
    owner: "Diego P.",
    plan: "Pro",
    status: "suspended",
    mrr: 760,
    createdAt: "2026-02-14",
    lastAccess: "2026-09-03 10:20",
    professionals: 3,
    customers: 55,
    utilization: 55,
    churnRisk: "medium",
  },
];

export const establishmentDetails: Record<string, EstablishmentDetail> = {
  "est-1": {
    ...establishments[0],
    ltv: 12800,
    nextBilling: "2026-10-05",
    activeDays: 140,
    dau: 42,
    wau: 128,
    mau: 164,
    totalPaid: 12840,
    failedPayments: 3,
    refunds: 1,
    riskScore: 12,
    mrrAtRisk: 0,
    riskReasons: [],
    usage: {
      appointments: 640,
      clients: 128,
      professionals: 4,
      services: 18,
      products: 12,
      campaigns: 3,
      markaAiSessions: 86,
      sessions: 920,
    },
    engagement: {
      dau: 42,
      wau: 128,
      mau: 164,
      activeDays: 72,
      sessions: 920,
    },
  },
  "est-2": {
    ...establishments[1],
    ltv: 0,
    nextBilling: "—",
    activeDays: 8,
    dau: 8,
    wau: 22,
    mau: 34,
    totalPaid: 0,
    failedPayments: 0,
    refunds: 0,
    riskScore: 48,
    mrrAtRisk: 0,
    riskReasons: [],
    usage: {
      appointments: 34,
      clients: 34,
      professionals: 2,
      services: 6,
      products: 4,
      campaigns: 0,
      markaAiSessions: 12,
      sessions: 90,
    },
    engagement: {
      dau: 8,
      wau: 22,
      mau: 34,
      activeDays: 5,
      sessions: 90,
    },
  },
  "est-3": {
    ...establishments[2],
    ltv: 18500,
    nextBilling: "2026-09-12",
    activeDays: 310,
    dau: 28,
    wau: 74,
    mau: 98,
    totalPaid: 31200,
    failedPayments: 17,
    refunds: 4,
    riskScore: 82,
    mrrAtRisk: 1240,
    riskReasons: ["Baixa utilização", "Login irregular"],
    usage: {
      appointments: 880,
      clients: 210,
      professionals: 6,
      services: 22,
      products: 8,
      campaigns: 1,
      markaAiSessions: 40,
      sessions: 640,
    },
    engagement: {
      dau: 28,
      wau: 74,
      mau: 98,
      activeDays: 41,
      sessions: 640,
    },
  },
  "est-4": {
    ...establishments[3],
    ltv: 52000,
    nextBilling: "2026-10-01",
    activeDays: 420,
    dau: 120,
    wau: 280,
    mau: 340,
    totalPaid: 98000,
    failedPayments: 2,
    refunds: 0,
    riskScore: 8,
    mrrAtRisk: 0,
    riskReasons: [],
    usage: {
      appointments: 2100,
      clients: 420,
      professionals: 11,
      services: 45,
      products: 30,
      campaigns: 12,
      markaAiSessions: 420,
      sessions: 3400,
    },
    engagement: {
      dau: 120,
      wau: 280,
      mau: 340,
      activeDays: 180,
      sessions: 3400,
    },
  },
};

export const users = [
  {
    id: "u1",
    name: "Ana Costa",
    establishment: "Studio Bella",
    type: "Owner",
    status: "ativo",
    lastLogin: "2026-09-05 09:10",
    createdAt: "2026-06-12",
    activity: "Hoje",
  },
  {
    id: "u2",
    name: "Maria Finance",
    establishment: "marka.ia",
    type: "Admin",
    status: "ativo",
    lastLogin: "2026-09-05 08:00",
    createdAt: "2025-01-10",
    activity: "Hoje",
  },
  {
    id: "u3",
    name: "João Lima",
    establishment: "Casa & Arte",
    type: "Manager",
    status: "ativo",
    lastLogin: "2026-09-04 21:12",
    createdAt: "2026-08-28",
    activity: "Ontem",
  },
  {
    id: "u4",
    name: "Carlos R.",
    establishment: "Nuvem Studio",
    type: "Professional",
    status: "ativo",
    lastLogin: "2026-09-03 14:20",
    createdAt: "2025-08-19",
    activity: "3d",
  },
  {
    id: "u5",
    name: "Pedro Staff",
    establishment: "Studio Bella",
    type: "Staff",
    status: "inativo",
    lastLogin: "2026-08-20 11:00",
    createdAt: "2026-03-01",
    activity: "8d",
  },
  {
    id: "u6",
    name: "Lívia Customer",
    establishment: "—",
    type: "Customer",
    status: "ativo",
    lastLogin: "2026-09-02 16:40",
    createdAt: "2026-07-15",
    activity: "Hoje",
  },
];

export const plansDetailed = [
  {
    id: "pro",
    name: "Pro",
    subscribers: 78,
    active: 71,
    trial: 7,
    mrr: 18420,
    revenueShare: 38,
    arpu: 236,
    churn: 1.2,
    upgradeRate: 4.1,
    downgradeRate: 1.8,
    trialToPaid: 22.4,
    ltv: 2480,
  },
  {
    id: "starter",
    name: "Starter",
    subscribers: 96,
    active: 88,
    trial: 8,
    mrr: 12120,
    revenueShare: 25,
    arpu: 126,
    churn: 2.4,
    upgradeRate: 1.5,
    downgradeRate: 3.1,
    trialToPaid: 18.2,
    ltv: 980,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    subscribers: 12,
    active: 11,
    trial: 1,
    mrr: 13200,
    revenueShare: 27,
    arpu: 1200,
    churn: 0.4,
    upgradeRate: 6.0,
    downgradeRate: 0.3,
    trialToPaid: 41.0,
    ltv: 9800,
  },
  {
    id: "trial",
    name: "Trial",
    subscribers: 34,
    active: 0,
    trial: 34,
    mrr: 0,
    revenueShare: 10,
    arpu: 0,
    churn: 0,
    upgradeRate: 0,
    downgradeRate: 0,
    trialToPaid: 34,
    ltv: 0,
  },
];

export const subscriptions = [
  {
    id: "sub-1",
    customer: "Studio Bella",
    establishment: "Studio Bella",
    plan: "Pro",
    status: "active" as const,
    mrr: 890,
    createdAt: "2026-06-12",
    nextBilling: "2026-10-05",
  },
  {
    id: "sub-2",
    customer: "Nuvem Studio",
    establishment: "Nuvem Studio",
    plan: "Enterprise",
    status: "active" as const,
    mrr: 2680,
    createdAt: "2025-08-19",
    nextBilling: "2026-10-01",
  },
  {
    id: "sub-3",
    customer: "Casa & Arte",
    establishment: "Casa & Arte",
    plan: "Starter",
    status: "trial" as const,
    mrr: 0,
    createdAt: "2026-08-28",
    nextBilling: "—",
  },
  {
    id: "sub-4",
    customer: "Loja Norte",
    establishment: "Loja Norte",
    plan: "Pro",
    status: "past_due" as const,
    mrr: 1240,
    createdAt: "2025-11-03",
    nextBilling: "2026-09-10",
  },
  {
    id: "sub-5",
    customer: "Bar da Rua",
    establishment: "Bar da Rua",
    plan: "Starter",
    status: "canceled" as const,
    mrr: 240,
    createdAt: "2025-12-01",
    nextBilling: "—",
  },
  {
    id: "sub-6",
    customer: "Luz & Formato",
    establishment: "Luz & Formato",
    plan: "Pro",
    status: "paused" as const,
    mrr: 760,
    createdAt: "2026-02-14",
    nextBilling: "2026-09-20",
  },
];

export const payments = [
  {
    id: "pay-1",
    customer: "Studio Bella",
    establishment: "Studio Bella",
    value: 890,
    method: "PIX" as const,
    status: "approved" as const,
    date: "2026-09-05",
  },
  {
    id: "pay-2",
    customer: "Nuvem Studio",
    establishment: "Nuvem Studio",
    value: 2680,
    method: "card" as const,
    status: "approved" as const,
    date: "2026-09-04",
  },
  {
    id: "pay-3",
    customer: "Loja Norte",
    establishment: "Loja Norte",
    value: 1240,
    method: "PIX" as const,
    status: "failed" as const,
    date: "2026-09-04",
  },
  {
    id: "pay-4",
    customer: "Casa & Arte",
    establishment: "Casa & Arte",
    value: 0,
    method: "PIX" as const,
    status: "pending" as const,
    date: "2026-09-05",
  },
  {
    id: "pay-5",
    customer: "Luz & Formato",
    establishment: "Luz & Formato",
    value: 760,
    method: "boleto" as const,
    status: "refunded" as const,
    date: "2026-08-28",
  },
];

export const financeMetrics = [
  { label: "Receita", value: "R$ 48.260", delta: 4.2 },
  { label: "Receita líquida", value: "R$ 46.100", delta: 3.8 },
  { label: "MRR", value: "R$ 48.260", delta: 4.2 },
  { label: "ARR", value: "R$ 579.120", delta: 3.1 },
  { label: "Taxas", value: "R$ 2.840", delta: -1.2 },
  { label: "Refunds", value: "R$ 420", delta: 0.4 },
  { label: "Recorrente", value: "R$ 44.100", delta: 5.0 },
  { label: "Margem", value: "62%", delta: 1.1 },
];

export const churnRiskRows = [
  {
    id: "cr-1",
    establishment: "Loja Norte",
    plan: "Pro",
    mrr: 1240,
    riskScore: 82,
    lastLogin: "2026-09-01 11:04",
    utilization: 67,
    utilizationDelta: -12,
    reasons: ["Baixa utilização", "Login irregular"],
  },
  {
    id: "cr-2",
    establishment: "Bar da Rua",
    plan: "Starter",
    mrr: 240,
    riskScore: 76,
    lastLogin: "2026-08-22 14:00",
    utilization: 12,
    utilizationDelta: -4,
    reasons: ["Encerramento do negócio"],
  },
  {
    id: "cr-3",
    establishment: "Casa & Arte",
    plan: "Starter",
    mrr: 0,
    riskScore: 48,
    lastLogin: "2026-09-04 21:12",
    utilization: 41,
    utilizationDelta: 5,
    reasons: ["Trial sem ativação"],
  },
  {
    id: "cr-4",
    establishment: "Luz & Formato",
    plan: "Pro",
    mrr: 760,
    riskScore: 36,
    lastLogin: "2026-09-03 10:20",
    utilization: 55,
    utilizationDelta: 1,
    reasons: ["Pausa"],
  },
];

export const alerts = [
  {
    id: "al1",
    severity: "critical" as const,
    title: "Taxa de pagamentos falhos aumentou significativamente.",
    description: "Failure rate em 4,8% nos últimos 7 dias.",
    cta: "Ver payments",
  },
  {
    id: "al2",
    severity: "warning" as const,
    title: "Churn do plano Pro aumentou.",
    description: "Churn de 1,2% para 1,9% em 14 dias.",
    cta: "Analisar churn",
  },
  {
    id: "al3",
    severity: "opportunity" as const,
    title: "Trial → Paid aumentou 12%.",
    description: "Funil de conversão melhora em 3 semanas.",
    cta: "Ver acquisition",
  },
  {
    id: "al4",
    severity: "info" as const,
    title: "Novo estabelecimento cadastrado.",
    description: "Casa & Arte entrou em trial.",
    cta: "Ver establishments",
  },
];

export const supportTickets = [
  {
    id: "sup-1",
    customer: "Studio Bella",
    establishment: "Studio Bella",
    type: "billing",
    status: "open",
    priority: "high",
    subject: "Assinatura past due",
    createdAt: "2026-09-05 08:20",
  },
  {
    id: "sup-2",
    customer: "Loja Norte",
    establishment: "Loja Norte",
    type: "technical",
    status: "in_progress",
    priority: "medium",
    subject: "Login irregular e re-login",
    createdAt: "2026-09-04 16:10",
  },
  {
    id: "sup-3",
    customer: "Casa & Arte",
    establishment: "Casa & Arte",
    type: "onboarding",
    status: "open",
    priority: "low",
    subject: "Trial sem ativação",
    createdAt: "2026-09-03 11:45",
  },
  {
    id: "sup-4",
    customer: "Nuvem Studio",
    establishment: "Nuvem Studio",
    type: "billing",
    status: "resolved",
    priority: "low",
    subject: "Invoice PIX re-processado",
    createdAt: "2026-09-01 09:00",
  },
];

export const administrators = [
  {
    id: "a1",
    name: "Maria Finance",
    role: "Finance" as const,
    status: "ativo",
    lastLogin: "2026-09-05 08:00",
    recentActions: 12,
  },
  {
    id: "a2",
    name: "Lucas Ops",
    role: "Operations" as const,
    status: "ativo",
    lastLogin: "2026-09-05 07:40",
    recentActions: 8,
  },
  {
    id: "a3",
    name: "Pedro Super",
    role: "Super Admin" as const,
    status: "ativo",
    lastLogin: "2026-09-04 22:10",
    recentActions: 24,
  },
  {
    id: "a4",
    name: "Ana Read",
    role: "Read Only" as const,
    status: "inativo",
    lastLogin: "2026-08-30 11:00",
    recentActions: 0,
  },
];

export const auditLogs = [
  {
    id: "log-1",
    at: "2026-09-05 09:14",
    admin: "Maria Finance",
    action: "alteração de plano",
    entity: "Studio Bella",
    result: "sucesso",
    ip: "—",
  },
  {
    id: "log-2",
    at: "2026-09-05 08:00",
    admin: "Lucas Ops",
    action: "login",
    entity: "marka.ia",
    result: "sucesso",
    ip: "192.168.1.10",
  },
  {
    id: "log-3",
    at: "2026-09-04 16:40",
    admin: "Maria Finance",
    action: "alteração de configuração",
    entity: "plans",
    result: "sucesso",
    ip: "—",
  },
  {
    id: "log-4",
    at: "2026-09-04 10:20",
    admin: "Pedro Super",
    action: "bloqueio",
    entity: "Bar da Rua",
    result: "sucesso",
    ip: "—",
  },
];

export const customers = [
  {
    id: "c1",
    name: "Client A",
    total: 42,
    status: "ativo",
    bookings: 18,
    ticket: 120,
    repeat: 0.62,
  },
  {
    id: "c2",
    name: "Client B",
    total: 18,
    status: "ativo",
    bookings: 9,
    ticket: 90,
    repeat: 0.41,
  },
  {
    id: "c3",
    name: "Client C",
    total: 7,
    status: "cancelado",
    bookings: 2,
    ticket: 60,
    repeat: 0.15,
  },
  {
    id: "c4",
    name: "Client D",
    total: 31,
    status: "ativo",
    bookings: 22,
    ticket: 150,
    repeat: 0.71,
  },
  {
    id: "c5",
    name: "Client E",
    total: 12,
    status: "no-show",
    bookings: 4,
    ticket: 80,
    repeat: 0.22,
  },
];

export const acquisitionFunnel = [
  { label: "Visitantes", value: 18420 },
  { label: "Leads", value: 3120 },
  { label: "Signups", value: 980 },
  { label: "Ativação", value: 420 },
  { label: "Trial", value: 210 },
  { label: "Pagamento", value: 96 },
];

export const acquisitionChannels = [
  { label: "Meta", value: 42 },
  { label: "Google", value: 28 },
  { label: "Organic", value: 16 },
  { label: "Referral", value: 8 },
  { label: "Affiliates", value: 4 },
  { label: "Outbound", value: 2 },
];

export const retentionCohorts = [
  { month: "Jan", m1: 100, m2: 92, m3: 88, m4: 84, m5: 80, m6: 76 },
  { month: "Fev", m1: 100, m2: 90, m3: 85, m4: 81, m5: 78, m6: null },
  { month: "Mar", m1: 100, m2: 91, m3: 86, m4: 82, m5: null, m6: null },
  { month: "Abr", m1: 100, m2: 94, m3: 89, m4: null, m5: null, m6: null },
];

export const productUsage = [
  { feature: "Agenda", adoption: 92, growth: 4.1 },
  { feature: "Clientes", adoption: 88, growth: 2.4 },
  { feature: "Financeiro", adoption: 74, growth: 1.8 },
  { feature: "CRM", adoption: 61, growth: 3.2 },
  { feature: "Marketing", adoption: 48, growth: -0.8 },
  { feature: "Estoque", adoption: 35, growth: 0.4 },
  { feature: "Profissionais", adoption: 71, growth: 2.1 },
  { feature: "marka AI", adoption: 54, growth: 8.6 },
];

export const churnBreakdown = [
  { reason: "Preço", share: 28 },
  { reason: "Baixa utilização", share: 22 },
  { reason: "Funcionalidades", share: 18 },
  { reason: "Problemas técnicos", share: 14 },
  { reason: "Concorrente", share: 10 },
  { reason: "Outros", share: 8 },
];
