import type { Permission, Role } from "./types";

const ALL: Permission[] = [
  "overview",
  "establishments",
  "establishment_detail",
  "users",
  "plans",
  "subscriptions",
  "payments",
  "finance",
  "customers",
  "product_usage",
  "acquisition",
  "retention",
  "churn",
  "churn_risk",
  "alerts",
  "audit_logs",
  "support",
  "administrators",
  "settings",
  "impersonate",
  "ambassadors",
];

const ROLES: Record<Role, Permission[]> = {
  super_admin: ALL,
  finance: [
    "overview",
    "establishments",
    "establishment_detail",
    "plans",
    "subscriptions",
    "payments",
    "finance",
    "churn",
    "alerts",
    "audit_logs",
    "settings",
    "ambassadors",
  ],
  support: [
    "overview",
    "establishments",
    "establishment_detail",
    "users",
    "customers",
    "churn_risk",
    "alerts",
    "audit_logs",
    "support",
    "impersonate",
  ],
  operations: [
    "overview",
    "establishments",
    "establishment_detail",
    "users",
    "plans",
    "subscriptions",
    "payments",
    "finance",
    "product_usage",
    "churn",
    "churn_risk",
    "alerts",
    "audit_logs",
    "support",
    "ambassadors",
  ],
  product: [
    "overview",
    "establishments",
    "establishment_detail",
    "product_usage",
    "acquisition",
    "retention",
    "churn",
    "alerts",
    "audit_logs",
    "settings",
  ],
  read_only: [
    "overview",
    "establishments",
    "establishment_detail",
    "users",
    "plans",
    "subscriptions",
    "payments",
    "finance",
    "customers",
    "product_usage",
    "acquisition",
    "retention",
    "churn",
    "churn_risk",
    "alerts",
    "audit_logs",
    "support",
  ],
};

export function canAccess(role: Role, permission: Permission) {
  return Boolean(ROLES[role]?.includes(permission));
}
